# Generated by Django 5.0.6 on 2024-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('Description', models.TextField(default='')),
                ('product_app', models.TextField(default='')),
                ('category', models.CharField(choices=[('DF', 'DOG_FOOD'), ('DT', 'DOG_TOYS'), ('CF', 'CAT_FOOD'), ('CT', 'CAT_TOYS'), ('GP', 'GROOMING_PRODUCTS'), ('BP', 'BATHING_PRODUCTS'), ('OP', 'OTHER_PRODUCTS')], max_length=2)),
            ],
        ),
    ]
