# Generated by Django 5.0.6 on 2024-06-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='composition',
            field=models.TextField(default=''),
        ),
    ]
