# Generated by Django 5.0.6 on 2024-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('DF', 'DOG_FOOD'), ('DT', 'DOG_TOYS'), ('DL', 'DOG_LEASH'), ('DH', 'DOG_HARNESS'), ('DB', 'DOG_BELT'), ('DBP', 'DOG_BATH_PRODUCTS'), ('CF', 'CAT_FOOD'), ('CT', 'CAT_TOYS'), ('CL', 'CAT_LEASH'), ('CH', 'CAT_HARNESS'), ('CB', 'CAT_BELT'), ('CBP', 'CAT_BATH_PRODUCTS'), ('GP', 'GROOMING_PRODUCTS'), ('OP', 'OTHER_PRODUCTS')], max_length=3),
        ),
    ]
