# Generated by Django 5.0.6 on 2024-06-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_payment_signature_id_alter_orderplaced_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
    ]
