# Generated by Django 5.0.6 on 2024-08-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_whishlist_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('DF', 'DOG FOOD'), ('DT', 'DOG TOYS'), ('DL', 'DOG LEASH'), ('DH', 'DOG HARNESS'), ('DB', 'DOG BELT'), ('DBP', 'DOG BATH PRODUCTS'), ('CF', 'CAT_FOOD'), ('CT', 'CAT_TOYS'), ('CL', 'CAT_LEASH'), ('CH', 'CAT_HARNESS'), ('CB', 'CAT_BELT'), ('CBP', 'CAT_BATH_PRODUCTS'), ('GP', 'GROOMING_PRODUCTS'), ('OP', 'OTHER_PRODUCTS')], max_length=3),
        ),
    ]
