# Generated by Django 5.0.6 on 2024-08-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('DF', 'DOG FOOD'), ('DT', 'DOG TOYS'), ('DL', 'DOG LEASH'), ('DH', 'DOG HARNESS'), ('DB', 'DOG BELT'), ('DBP', 'DOG BATH PRODUCTS'), ('CF', 'CAT FOOD'), ('CT', 'CAT TOYS'), ('CL', 'CAT LEASH'), ('CH', 'CAT HARNESS'), ('CB', 'CAT BELT'), ('CBP', 'CAT BATH PRODUCTS'), ('GP', 'GROOMING PRODUCTS'), ('OP', 'OTHER PRODUCTS')], max_length=3),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/extra_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='app.products')),
            ],
        ),
    ]
